from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Severity(str, Enum):
    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"


class VulnerabilityItem(BaseModel):
    title: str
    tool_source: str
    severity: Severity
    target_url: str
    cwe: Optional[str] = None
    cve: Optional[str] = None
    cvss: Optional[str] = None
    owasp_category: Optional[str] = None
    raw_evidence: Optional[str] = None
    request_payload: Optional[str] = None
    generated_poc: Optional[str] = None
    remediation: Optional[str] = None
    secure_code_fix: Optional[str] = Field(
        default=None,
        description="Secure code example generated by the AI enrichment pipeline",
    )
    capec: Optional[str] = Field(
        default=None,
        description="CAPEC attack pattern ID enriched by the AI pipeline",
    )
    references: list[str] = Field(default_factory=list)
    mitre_attack: Optional[str] = Field(
        default=None,
        description="MITRE ATT&CK technique ID enriched by the AI pipeline",
    )
    package_name: Optional[str] = None
    installed_version: Optional[str] = None
    fixed_version: Optional[str] = None
    exploitability: Optional[str] = None
    affected_file: Optional[str] = None


class SeverityBreakdown(BaseModel):
    critical: int = 0
    high: int = 0
    medium: int = 0
    low: int = 0


class ScanSummaryMetrics(BaseModel):
    total_raw_findings: int
    unique_findings: int
    deduplicated_count: int
    severity_breakdown: SeverityBreakdown
    tools_detected: list[str]


class ScanAnalysisMetadata(BaseModel):
    """Read-only execution details returned with a completed analysis."""

    detected_scanner: str | None = None
    ai_provider: str = "OpenRouter"
    ai_model: str | None = None
    processing_duration_ms: int | None = None
    historical_summary: "HistoricalFindingSummary | None" = None


class HistoricalFindingSummary(BaseModel):
    """Comparison of this scan with the prior completed scan in a project."""

    new_findings: int = 0
    resolved_findings: int = 0
    recurring_findings: int = 0
    risk_trend: str = "new"


class ScanAnalysisResponse(BaseModel):
    findings: list[VulnerabilityItem]
    summary: ScanSummaryMetrics
    analysis_metadata: ScanAnalysisMetadata | None = None


class ReportMetadata(BaseModel):
    company_name: str = "VulnPilot AI Client"
    assessment_date: str
    assessment_scope: str = "Latest uploaded scan artifacts"
    assessment_type: str = "Vulnerability Assessment"
    classification: str = "Confidential"


class ReportGenerateRequest(BaseModel):
    metadata: ReportMetadata
